### ISSUE TITLE
mvn package error

### ISSUE THREAD

**Issue by wuzunqian** [apache/incubator-servicecomb-saga#176]
mvn clean install -DskipTests

Apache Maven 3.5.3 (3383c37e1f9e9b3bc3df5050c29c8aff9f295297; 2018-02-25T03:49:05+08:00)
Maven home: /usr/local/Cellar/maven/3.5.3/libexec
Java version: 1.8.0_162, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/jre
Default locale: en_CN, platform encoding: UTF-8
OS name: "mac os x", version: "10.13.3", arch: "x86_64", family: "mac"

[ERROR] Failed to execute goal org.xolstice.maven.plugins:protobuf-maven-plugin:0.5.0:compile (default) on project pack-contract-grpc: protoc did not exit cleanly. Review output for more information. -> [Help 1]

**Comment by wuzunqian** [comment]
已解决 没问题了

**Comment by WillemJiang** [comment]
I  cannot reproduce the error on Mac OSX.

 mvn -version
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-11T00:41:47+08:00)
Maven home: /usr/local/Cellar/maven/3.3.9/libexec
Java version: 1.8.0_151, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.12.6", arch: "x86_64", family: "mac"

**Comment by wuzunqian** [comment]
最后发现是本地仓库jar包损坏，重新下载可以了
