### ISSUE TITLE
saga support dubbo or not?

### ISSUE THREAD

**Issue by wuzunqian** [apache/incubator-servicecomb-saga#177]
can i use saga with dubbo? i test it and found dubbo will always timeout, i think may be something conflict, does anyone have a try?
有没有人尝试将saga用于dubbo服务？从原理上来说应该是可以的， 但测试了下会导致dubbo总是超时

**Comment by wuzunqian** [comment]
thank u for your reply, i add dubbo filter to pass omega context from consumer to provider, and it seems work fine now.

**Comment by WillemJiang** [comment]
@wuzunqian  Do you mind to submit a PR for it?
I think there are lots of Dubbo users want to use this feature.

**Comment by wuzunqian** [comment]
@WillemJiang ok, i will fork and submit a PR when i was free

**Comment by WillemJiang** [comment]
@wuzunqian Great, I'm looking forward you PR.

**Comment by WillemJiang** [comment]
@wuzunqian  Here is the JIRA  https://issues.apache.org/jira/browse/SCB-245  for it.
If you add SCB-245 in you PR log, the PR record will be sent to JIRA automatically.
