### ISSUE TITLE
Can i use feign and saga in project ?

### ISSUE THREAD

**Issue by JokerLoveAllen** [apache/incubator-servicecomb-saga#183]
in our project , use feign ,but we can use saga ?

**Comment by WillemJiang** [comment]
As Zipkin supports the feign out of box, I don't think there is a big challenge here.
You just need to do something to pass omega context around the framework as we do in https://github.com/apache/incubator-servicecomb-saga/pull/180.

**Comment by JokerLoveAllen** [comment]
The result of running saga-demo is wrong, soga is not executed correctly.The car's 'cancelled' state does not become true when I enter the wrong information, can u help me?
url: http://localhost:8081/booking/喜马拉雅/333/80
resp: {
    "name": "喜马拉雅",
    "amount": 80,
    "confirmed": true,
    "cancelled": false
 }

**Comment by WillemJiang** [comment]
Hi, 
I don't think this is a related issue, but I will try to run the demo myself.
