### ISSUE TITLE
Saga executes compensation, but excludes interface which throws exception.

### ISSUE THREAD

**Issue by Gannalyo** [apache/incubator-servicecomb-saga#221]
### Does the compensation depends on Spring Transaction?
I defined an compensable interface without Spring Transaction, but it didn't call rollback method when produced an exception in it.

My code:
```
@Compensable(compensationMethod = "updateMoneyByUserId_rollback")
public int updateMoneyByUserId(@Param("userId") long userId, @Param("money") long money) {
	System.err.println("[" + sdf.format(new Date()) + "] 进入 " + this.getClass() + ".updateMoneyByUserId 提交方法……\t\tid = " + userId + ", money = " + money);
		
	int result = userRepository.updateMoneyByUserId(userId, money);// commit to update balance immediately
		
	Integer.parseInt("");
		
	return result;
}

public int updateMoneyByUserId_rollback(@Param("userId") long userId, @Param("money") long money) {
	System.err.println("[" + sdf.format(new Date()) + "] 进入 " + this.getClass() + ".rollback 补偿方法……\t\tid = " + userId + ", money = " + -money);
	return userRepository.updateMoneyByUserId(userId, -money);
}
````
Information for txevent data:
![image](https://user-images.githubusercontent.com/34175244/42742038-13350b86-88ea-11e8-839b-0a0a977aa896.png)

**Comment by WillemJiang** [comment]
Can you show us the big picture of the service invocation? 
Current Saga implementation won't call the compensation method of ServiceA when ServiceA through the exception.  You need to leverage spring transaction to revert the change in the call of ServiceA.

**Comment by Gannalyo** [comment]
@WillemJiang "You need to leverage spring transaction to revert the change in the call of ServiceA."
Okay, I got.

**Comment by WillemJiang** [comment]
@Gannalyo You can take the Dubbo demo as an example, the Transactional annotation could avoid the database commit if there is an exception throw. In this way we don't need to call the compensation method of ServiceA.  
Please close this issue if you got the answer.

**Comment by Gannalyo** [comment]
Right, it indeed save a call for the compensation of Service A. I have added the spring transaction for Service A, then it worked. Maybe Spring Cloud  was better than Dubbo & GRPC.
Okay, I'll close it right now. Thanks.
