### ISSUE TITLE
Several questions about repeated events.

### ISSUE THREAD

**Issue by Gannalyo** [apache/incubator-servicecomb-saga#228]
Q1: What problems the repeated SagaEndedEvent would cause?

Q2: It would write the same TxStartedEvent/TxEndedEvent in case of trying commit again.
    Then what was the idea for initial design?
    What problems the repeated TxStartedEvent/TxEndedEvent would cause?

Q3: Are there any other situations except above?

**Comment by WillemJiang** [comment]
Q1: As we have the EventScanner and the Saga starter caller to send the SagaEndedEvent. 
But it's no harm if there are more than two SagaEndedEvent as the Saga processing is ended eventually.  
Q2: The event should be logged incase of the service shutdown by accident.  

Q3: Currently I don't think there any other bad situations which we need to deal with.

**Comment by Gannalyo** [comment]
Okay, I got, thanks so much!
