### ISSUE TITLE
when AbortEvent is late

### ISSUE THREAD

**Issue by HuZheting** [apache/incubator-servicecomb-saga#253]
I write a test in AlphaIntegrationTest,
`
  public void whenAbortEventIsLate(){
      
      String sagaGlobalId = UUID.randomUUID().toString();
      String localIdEntry = UUID.randomUUID().toString();
      String localIdEndpoint = UUID.randomUUID().toString();
      
      String anotherSagaGlobalId = UUID.randomUUID().toString();
      String anotheEntryLocalId = UUID.randomUUID().toString();
      String anotherEndPointLocalId = UUID.randomUUID().toString();
      
      asyncStub.onConnected(serviceConfig, compensateResponseObserver);
      blockingStub.onTxEvent(someGrpcEvent(SagaStartedEvent, sagaGlobalId, localIdEntry));
      blockingStub.onTxEvent(someGrpcEvent(SagaStartedEvent, anotherSagaGlobalId, anotheEntryLocalId));
      
      blockingStub.onTxEvent(someGrpcEvent(TxStartedEvent, sagaGlobalId, localIdEndpoint));
      blockingStub.onTxEvent(someGrpcEvent(TxEndedEvent, sagaGlobalId, localIdEndpoint));
      await().atMost(1, SECONDS).until(() -> eventRepo.count() == 4);
      
      blockingStub.onTxEvent(someGrpcEvent(TxStartedEvent, anotherSagaGlobalId, anotherEndPointLocalId));
      blockingStub.onTxEvent(someGrpcEvent(TxEndedEvent, anotherSagaGlobalId, anotherEndPointLocalId));
      blockingStub.onTxEvent(someGrpcEvent(TxAbortedEvent, anotherSagaGlobalId, anotherEndPointLocalId));
      
      
      await().atMost(2, SECONDS).until(() -> !receivedCommands.isEmpty());
      
      blockingStub.onTxEvent(someGrpcEvent(TxAbortedEvent, sagaGlobalId, anotheEntryLocalId));
      
      await().atMost(10, SECONDS).until(() -> receivedCommands.size() > 1);
      assertThat(receivedCommands.size(), is(2));
  }`
and the test fail.
![image](https://user-images.githubusercontent.com/9289881/44245949-280d4400-a20e-11e8-9992-08b1df7442d3.png)

It seems that the first uncompensate tx  can not be found if another abort event has been found.
I believe that the variable "nextEndedEventId" cause this problem.

**Comment by WillemJiang** [comment]
Normally the TxStartedEvent can only come with TxEndedEvent or TxAbortedEvent.
If you send the event like this 
```
blockingStub.onTxEvent(someGrpcEvent(TxStartedEvent, anotherSagaGlobalId, anotherEndPointLocalId));
  blockingStub.onTxEvent(someGrpcEvent(TxEndedEvent, anotherSagaGlobalId, anotherEndPointLocalId));
  blockingStub.onTxEvent(someGrpcEvent(TxAbortedEvent, anotherSagaGlobalId, anotherEndPointLocalId));
  
```
Alpha Server cannot tell if the TxEvent is right or not.  BTW, Alpha Server won't componestate the other event if they are not share the same global transaction id.

**Comment by HuZheting** [comment]
what I mean is that the bigger surrogateId will update  the variable "nextEndedEventId" and alpha cannot find the smaller one.

> eventRepository.findFirstUncompensatedEventByIdGreaterThan(nextEndedEventId, TxEndedEvent.name())
        .forEach(event -> {
          LOG.info("Found uncompensated event {}", event);
          nextEndedEventId = event.id();
          commandRepository.saveCompensationCommands(event.globalTxId());
        });
@Query("SELECT t FROM TxEvent t "
      + "WHERE t.type = ?1 AND t.surrogateId > ?2 AND EXISTS ( "
      + "  SELECT t1.globalTxId FROM TxEvent t1 "
      + "  WHERE t1.globalTxId = t.globalTxId "
      + "    AND t1.type = 'TxAbortedEvent' AND NOT EXISTS ( "
      + "    SELECT t2.globalTxId FROM TxEvent t2 "
      + "    WHERE t2.globalTxId = t1.globalTxId "
      + "      AND t2.localTxId = t1.localTxId "
      + "      AND t2.type = 'TxStartedEvent' "
      + "      AND t2.creationTime > t1.creationTime)) AND NOT EXISTS ( "
      + "  SELECT t3.globalTxId FROM TxEvent t3 "
      + "  WHERE t3.globalTxId = t.globalTxId "
      + "    AND t3.localTxId = t.localTxId "
      + "    AND t3.type = 'TxCompensatedEvent') AND ( "
      + "  SELECT MIN(t4.retries) FROM TxEvent t4 "
      + "  WHERE t4.globalTxId = t.globalTxId "
      + "    AND t4.localTxId = t.localTxId "
      + "    AND t4.type = 'TxStartedEvent' ) = 0 "
      + "ORDER BY t.surrogateId ASC")
  List<TxEvent> findFirstByTypeAndSurrogateIdGreaterThan(String type, long surrogateId, Pageable pageable);

Take the saga-spring-demo as example.
There are two request at the same time. They firstly invoke the car service and succeed. Then they invoke the hotel service，but the hotel service fail.
if we can't ensure the order of message of two different invocations, Alpha may receive messages in the following order：
<img width="673" alt="5c1da0985073e2642b6429432d974011" src="https://user-images.githubusercontent.com/9289881/44309435-294e9480-a3f9-11e8-8755-cdfb02d6bd66.png">

`


    String sagaGlobalId = UUID.randomUUID().toString(); //Request1
    String bookingApplicationLocalId = UUID.randomUUID().toString();
    String carServiceLocalId = UUID.randomUUID().toString();
    String hotelServiceLocalId = UUID.randomUUID().toString();

    String anotherSagaGlobalId = UUID.randomUUID().toString();//Request2
    String anotheBookingApplicationLocalId = UUID.randomUUID().toString();
    String anotherCarServiceLocalId = UUID.randomUUID().toString();
    String anotherHoterServceiLocalId = UUID.randomUUID().toString();

    asyncStub.onConnected(serviceConfig, compensateResponseObserver);

    blockingStub.onTxEvent(someGrpcEvent(SagaStartedEvent, sagaGlobalId, bookingApplicationLocalId));
    blockingStub.onTxEvent(someGrpcEvent(SagaEndedEvent, anotherSagaGlobalId, anotheBookingApplicationLocalId));

    blockingStub.onTxEvent(someGrpcEvent(TxStartedEvent, sagaGlobalId, carServiceLocalId));
    blockingStub.onTxEvent(someGrpcEvent(TxEndedEvent, sagaGlobalId, carServiceLocalId));//surrogateId --> 4

    blockingStub.onTxEvent(someGrpcEvent(TxStartedEvent, anotherSagaGlobalId, anotherCarServiceLocalId));
    blockingStub.onTxEvent(someGrpcEvent(TxEndedEvent, anotherSagaGlobalId, anotherCarServiceLocalId));//surrogateId --> 6

    blockingStub.onTxEvent(someGrpcEvent(TxStartedEvent, sagaGlobalId, hotelServiceLocalId));
    blockingStub.onTxEvent(someGrpcEvent(TxStartedEvent, anotherSagaGlobalId, anotherHoterServceiLocalId));

    //the latter hotelservice abort event come first
    blockingStub.onTxEvent(someGrpcEvent(TxAbortedEvent, anotherSagaGlobalId, anotherHoterServceiLocalId));
    await().atMost(2, SECONDS).until(() -> !receivedCommands.isEmpty());

    assertThat(receivedCommands.poll().getGlobalTxId(), is(anotherSagaGlobalId));

    //the TxAbortedEvent of the first hotelservice TxAbortedEvent didn't come until the previous TxAbortedEvent has been found
    blockingStub.onTxEvent(someGrpcEvent(TxAbortedEvent, sagaGlobalId, hotelServiceLocalId));

    //now, the variable "nextEndedEventId" is 6, so the TxEndedEvent whose surrogateId is 4 can't be found.
    await().atMost(10, SECONDS).until(() -> receivedCommands.size() > 1);
    assertThat(receivedCommands.size(), is(2));
`

**Comment by HuZheting** [comment]
and in the first test
"blockingStub.onTxEvent(someGrpcEvent(TxAbortedEvent, sagaGlobalId, anotheEntryLocalId));"
should be 
"blockingStub.onTxEvent(someGrpcEvent(TxAbortedEvent, sagaGlobalId, localIdEntry));"
I am sorry.
just look at the saga-spring-demo example.

**Comment by WillemJiang** [comment]
@HuZheting  Thanks for pointing that out, it's the issue that we are facing now. 
Now we are thinking to updated the Alpha to react the TxAbortedEvent directly, and we can get rid off the complex SQL.
