### ISSUE TITLE
An unusual problem for SagaEndedEvet

### ISSUE THREAD

**Issue by Gannalyo** [apache/incubator-servicecomb-saga#257]
Yesterday, it's very accurately to the data of the table 'txevent'. However, the 'creationTime' to 'SagaEndedEvent' were changed when I started the Alpha program.

In fact, it had happened many times before.

I apologize to this problem due to I didn't know how to make it happen again.

Please pay attention to it.
Thank you so much!

![image](https://user-images.githubusercontent.com/34175244/44317595-b8dd5d00-a464-11e8-802d-f843627be4f3.png)

**Comment by WillemJiang** [comment]
Thanks for pointing that out. 
The event scanner is trying to update the SagaEndEvent once the timeout happened. 
 As the SagaEndedEvent  won't effect the componsation process, this defect is harmless.  Now We are thinking to do some updates on the Alpha Server， this part of work could be rewroten.

**Comment by zhfeng** [comment]
It looks like this issue could be closed.
