### ISSUE TITLE
When TxEndedEvent comes after TxAbortedEvent, it would not be compensated?

### ISSUE THREAD

**Issue by Chenhaoqing** [apache/incubator-servicecomb-saga#281]
I write a test in AlphaIntegrationTest like this,
```Java
  @Test
  public void compensateTxEndedEventAfterOtherTxAborted() {
    String sagaGlobalId = UUID.randomUUID().toString();
    String bookingApplicationLocalId = UUID.randomUUID().toString();
    String carServiceLocalId = UUID.randomUUID().toString();
    String hotelServiceLocalId = UUID.randomUUID().toString();

    asyncStub.onConnected(serviceConfig, compensateResponseObserver);

    blockingStub
            .onTxEvent(someGrpcEvent(SagaStartedEvent, sagaGlobalId, bookingApplicationLocalId));

    blockingStub.onTxEvent(someGrpcEvent(TxStartedEvent, sagaGlobalId, carServiceLocalId));
    blockingStub.onTxEvent(someGrpcEvent(TxAbortedEvent, sagaGlobalId, carServiceLocalId));

    blockingStub.onTxEvent(someGrpcEvent(TxStartedEvent, sagaGlobalId, hotelServiceLocalId));
    blockingStub.onTxEvent(someGrpcEvent(TxEndedEvent, sagaGlobalId, hotelServiceLocalId));

    await().atMost(30, SECONDS).until(() -> receivedCommands.size() > 0); //fail here
    assertThat(receivedCommands.size(), is(1));

    GrpcCompensateCommand command = receivedCommands.poll();
    assertThat(command.getGlobalTxId(), is(sagaGlobalId));
    assertThat(command.getLocalTxId(), is(hotelServiceLocalId));
    assertThat(command.getParentTxId(), is(parentTxId));
    assertThat(command.getCompensationMethod(), is(compensationMethod));
    assertThat(command.getPayloads().toByteArray(), is(payload.getBytes()));
  }

```

is it a valid testcase？

**Comment by HuZheting** [comment]
If you have receive a TxAbortEvent, the next TxStartedEvent with same globalTxId will be rejected.
Look at the code in class TxConsistentService.

`

    public boolean handle(TxEvent event) {

    if (types.contains(event.type()) && isGlobalTxAborted(event)) {

      LOG.info("Transaction event {} rejected, because its parent with globalTxId {} was already aborted",
          event.type(), event.globalTxId());

      return false;

    }

    eventRepository.save(event);

    return true;

     }


`

**Comment by Chenhaoqing** [comment]
@HuZheting 
but when we have two or more omegas do the job simultaneously, it may occurs.

**Comment by WillemJiang** [comment]
As @HuZheting said, in current Alpha implementation it rejects the first start event once the abort event is received.
We may need to fix this corn case by updating the Alpha implementation.

**Comment by Chenhaoqing** [comment]
@HuZheting @WillemJiang

**Comment by Chenhaoqing** [comment]
@HuZheting @WillemJiang 
thanks for your reply.
I think I have a wrong testcase.
