### ISSUE TITLE
Is it possible for a service has many instance?

### ISSUE THREAD

**Issue by Chenhaoqing** [apache/incubator-servicecomb-saga#284]
https://github.com/apache/incubator-servicecomb-saga/blob/96d09dcec42cbde956809bab73e6ca6efff1dc40/alpha/alpha-server/src/main/java/org/apache/servicecomb/saga/alpha/server/tcc/registry/OmegaCallbacksRegistry.java#L80

If we have several instances with same OmegaCallback inside a service, then we would remove the wrong OmegaCallback possibly.

**Comment by WillemJiang** [comment]
Thanks for point that out, it's my bad. I will submit a quick fix for it.

**Comment by WillemJiang** [comment]
@Chenhaoqing  Thanks for pointing that out, I just went through the code, as we could get the omegaCallback if the original instance is not there.  It is possible to remove a wrong OmegaCallback instances.
I saw you submit a PR for it yesterday，I will merge it shortly.
