### ISSUE TITLE
docker pull alpha-server fail

### ISSUE THREAD

**Issue by gbKidCoding** [apache/incubator-servicecomb-saga#308]
从哪里下载alpha-server image

**Comment by WillemJiang** [comment]
We pushed the alpha-server 0.3.0-SNAPSHOT
https://hub.docker.com/r/servicecomb/alpha-server/

**Comment by WillemJiang** [comment]
You can build the docker image yourself with the below command after checkout the code.

mvn clean install -Pdemo,docker
