### ISSUE TITLE
请问alpha集群是怎么处理grpc双向流的

### ISSUE THREAD

**Issue by VitZhou** [apache/incubator-servicecomb-saga#323]
我看了源码,看到tcc的confirm事件是通过grpc的stream来实现服务器推送的. 而这个事件是在客户端发送了onTccEndedEvent事件之后触发的.那么如果alpha做了集群,客户端的请求就会负载到不同的服务端实例上;但是客户端的实例与服务端的双向流stream是1对1绑定的(从源码也可以看出你们在内存中保存了stream握手时的客户端信心).  那么请问,如果服务器的onTccEndedEvent事件并没有发送到与之握手的服务端实例上,服务端怎么通过stream来通知到客户端实例？

**Comment by zhfeng** [comment]
这个要依赖于alpha集群的实现方式。如果只是简单的用负载均衡的方式的话，现在的处理方式是需要改进的。之前在 [HA issue of service comb TCC workflow](https://lists.apache.org/thread.html/2ee4ac7b7402e3301aa27bf5907896730a8b8d465d89797b9d76dce4@%3Cdev.servicecomb.apache.org%3E) 上有过讨论，您有更好的建议可以加入mailing list和我们一起讨论！

**Comment by VitZhou** [comment]
那请问现在alpha的集群实现是怎样的？ 没有在设计文档上找到.

**Comment by WillemJiang** [comment]
If there is no Omega instance to listen to coordinate event, I don't think current Alpha implementation can handle this kind stutation. I just added a comment on the [JIRA](https://issues.apache.org/jira/projects/SCB/issues/SCB-990). 

Current implementation is based on the DB cluster and Alpha just store all the data into DB. In this way Alpha instance is stateless, but we need find a way to route the coordinate message to the right Omega instance, I'm open for discussion for this kind of feature. Please join the discussion in the mailing list by following the steps [here](http://servicecomb.apache.org/cn/developers/subscribe-mail-list/).

**Comment by zhfeng** [comment]
@VitZhou  is it OK to close this issue ?
