### ISSUE TITLE
Can alpha communicate with omega cluster using service discovery and loadbalance?

### ISSUE THREAD

**Issue by achu2000** [apache/incubator-servicecomb-saga#324]
thus when a omega instance down, alpha can still finish the global transaction.

**Comment by zhfeng** [comment]
sorry, I can not be very clear about your question. currently, there is no something like the omega cluster. I think if the omega instance is down, the alpha server will retry to send the message to see if the participant is recovered again. And the alpha server will rollback the transaction if it failed to communicate to the participants.

**Comment by achu2000** [comment]
for example，in workflow TCC Scenario
![workflow TCC Scenario](https://github.com/apache/incubator-servicecomb-saga/blob/master/docs/static_files/successful_scenario_TCC.png)
when service2&service3 try() is success, then service1 begin confirm(), then alpha begin call service2 and service3's confirm(). but when service3 is down, how to ensure the integrity of this transaction? In this scenario, alpha will not reach the service3's instance anymore,and will nerver rollback the services'3 branch transaction. So, we need to find out a way to reach another service3's instance, that's why I raised this issue.

**Comment by WillemJiang** [comment]
OK, I just create a JIRA[1] for it. We normally use JIRA to track the issue.
[1]https://issues.apache.org/jira/browse/SCB-990

**Comment by zhfeng** [comment]
I will close this issue since we have the SCB-990
