### ISSUE TITLE
Can I use "alpha" like use "spring clould" module the same and  registered to eureka ?

### ISSUE THREAD

**Issue by fenqinxyz** [apache/incubator-servicecomb-saga#328]

**Comment by WillemJiang** [comment]
Do you mean to use eureka to find the instance of alpha service?

**Comment by fenqinxyz** [comment]
Yes, support it?

**Comment by fenqinxyz** [comment]
OK Thanks

**Comment by WillemJiang** [comment]
#64 is for the centralized Saga implementation.  For the Alpha cluster, we have plan to introduce some other Service Discovery mechanism, I don't think we will use eureka by default.
